####################################################################
## ZOUPA - (ZombyMediaIC open source usage protection agreement)  ##
## License as of: 10.05.2020 19:41 | #202005101941                ##
## Niklas Vorberg (AsP3X)                                         ##
####################################################################
version: '2'

services:
  db:
    image: mariadb
    container_name: corespace_db_1
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=EZWK4ZPd4YsJpkjzKPkTe7vYge2UESa5vxAnudyWqG6w
      - MYSQL_PASSWORD=Zomby.0207
      - MYSQL_DATABASE=corespace
      - MYSQL_USER=corespace
    ports:
      - 3307:3306
    networks:
      - corespace
    volumes:
      - ./source/mysql-dump:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      timeout: 20s
      retries: 10
    logging:
      options:
        max-size: '12m'
        max-file: '5'
      driver: json-file

  api:
    image: zombymediaic/zapache2:latest
    volumes:
      - ./services/api/:/var/www/html/
    ports:
      - "2020:80"
    links:
      - db
    networks:
      - corespace
    restart: always

  # transaction:
  #   image: zombymediaic/xtranscore:1.0
  #   volumes:
  #     - ./services/transaction/core/:/programm/core
  #     - ./services/transaction/engine/:/programm/engine
  #   links:
  #     - db
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   restart: always
  #   networks:
  #     - corespace

  monitoring:
    image: zombymediaic/zapache2:1.4
    volumes:
      - ./services/monitoring/:/var/www/html/
    ports:
      - "2030:80"
    links:
      - db
    networks:
      - corespace
    restart: always

networks:
  corespace:
    external:
      name: corespace_backend
